<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <material name="green">
        <color rgba="0 0.8 0 1" /> <!-- Brighter green -->
    </material>

    <material name="grey">
        <color rgba="0.3 0.3 0.3 1" /> <!-- Darker grey -->
    </material>

    <link name="base_link" />

    <link name="de_link">
        <visual>
            <geometry>
                <mesh filename="package://my_robot_description/meshes/De.STL" scale = "0.01 0.01 0.01" />
            </geometry>
            <origin xyz="0 0 0" rpy="1.57 0 0"/>
            <material name="">
                <color rgba="1 0 0 1"/>
            </material>
        </visual>
    </link>

    <joint name="base_de_joint" type="fixed">
        <parent link="base_link" />
        <child link="de_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="than_link">
        <visual>
            <geometry>
                <mesh filename="package://my_robot_description/meshes/Than.STL" scale = "0.01 0.01 0.01"/>
            </geometry>
            <origin xyz="0 0 0" rpy="1.57 0 0"/>
            <material name="">
                <color rgba="0 0.7 0 0.3"/>
            </material>

        </visual>
    </link>

    <joint name="base_than_joint" type="fixed">
        <parent link="base_link" />
        <child link="than_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

</robot>




<!-- <?xml version = "1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name = "base_length" value = "0.6" />
    <xacro:property name = "base_width" value = "0.4" />
    <xacro:property name = "base_height" value = "0.2"/>
    <xacro:property name = "wheel_radius" value = "0.1"/>
    <xacro:property name = "wheel_length" value = "0.05"/>


    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz = "0 0 ${base_height / 2.0}" rpy = "0 0 0" />
            <material name = "green" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz = "0 0 ${base_height / 2.0}" rpy = "0 0 0" />
        </collision>
        <xacro:box_inertia m = "5.0" l = "${base_length}" w = "${base_width}" h = "${base_height}"
                           xyz = "0 0 ${base_height / 2.0}" rpy = "0 0 0" />
    </link>

    <xacro:macro name = "wheel_link" params = "prefix">
        <link name = "${prefix}_wheel_link" >
            <visual>
                <geometry>
                    <cylinder radius = "${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz = "0 0 0" rpy = "${pi / 2.0} 0 0"/>
                <material name = "gray" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius = "${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz = "0 0 0" rpy = "${pi / 2.0} 0 0"/>
            </collision>
            <xacro:cylinder_inertia m ="1.0" r="${wheel_radius}" h = "${wheel_length}" 
                                    xyz = "0 0 0" rpy = "${pi / 2.0} 0 0"/>
        </link>
    </xacro:macro>
    
    <xacro:wheel_link prefix = "right" />
    <xacro:wheel_link prefix = "left" />

    <joint name = "base_right_wheel_joint" type = "continuous">
        <parent link = "base_link"/>
        <child link = "right_wheel_link" />
        <origin xyz = "${-base_length / 4.0} ${-(base_width + 0.05) / 2.0} 0" rpy = "0 0 0"/>
        <axis xyz = "0 1 0"/>
    </joint>

    <joint name = "base_left_wheel_joint" type = "continuous">
        <parent link = "base_link"/>
        <child link = "left_wheel_link" />
        <origin xyz = "${-base_length / 4.0} ${(base_width + 0.05) / 2.0} 0" rpy = "0 0 0"/>
        <axis xyz = "0 1 0"/>
    </joint>

    <link name = "caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius = "${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <material name = "gray" />
        </visual>
        <collision>
            <geometry>
                <sphere radius = "${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
        </collision>
        <xacro:sphere_inertia m = "0.5" r = "${wheel_radius / 2.0}"
                              xyz = "0 0 0" rpy="0 0 0" />
    </link>

    <joint name = "base_caster_wheel_joint" type = "fixed">
        <parent link = "base_link"/>
        <child link = "caster_wheel_link" />
        <origin xyz = "${base_length / 3.0} 0 -0.05" rpy = "0 0 0"/>
    </joint>

    <link name = "base_footprint"/>

    <joint name = "base_footprint_joint" type = "fixed">
        <parent link = "base_footprint"/>
        <child link = "base_link"/>
        <origin xyz = "0 0 ${wheel_radius}" rpy = "0 0 0"/>
    </joint>
</robot> -->
